[package]
name = "test_utils"
version.workspace = true
edition.workspace = true

[dependencies]
# Just want to use whatever the parent crate is using
hyper = { workspace = true }
rand = { workspace = true }
